'use client'
import { createContext, useContext, useState, useEffect } from 'react'

const translations = {
  en: {
    // ── Nav ──────────────────────────────────────────────────────────────────
    dashboard:         'Dashboard',
    contacts:          'Contacts',
    servicesInventory: 'Services & Inventory',
    vehicles:          'Vehicles',
    bookings:          'Bookings',
    finance:           'Finance',
    accounting:        'Accounting',
    reports:           'Reports',
    settings:          'Settings',

    // ── Dashboard KPIs ───────────────────────────────────────────────────────
    totalProfit:       'Total Profit',
    totalRevenue:      'Total Revenue',
    totalExpenses:     'Total Expenses',
    lowStockAlerts:    'Low Stock Alerts',
    revenueMTD:        'Revenue MTD',
    activeBookings:    'Active Bookings',
    avgOrderValue:     'Avg Order Value',
    csatScore:         'CSAT Score',
    recentBookings:    'Recent Bookings',
    activityFeed:      'Activity Feed',
    currentMonth:      'Current Month',
    addChart:          'Add Chart',
    allInStock:        'all items in stock',
    noBookingsYet:     'No bookings yet',
    noActivityYet:     'No activity yet',
    today:             'Today',
    thisWeek:          'This Week',
    thisQuarter:       'This Quarter',
    thisYear:          'This Year',
    comingSoon:        'Coming soon',
    last10:            'Last 10',
    client:            'Client',
    service:           'Service',
    vehicle:           'Vehicle',
    amount:            'Amount',
    status:            'Status',

    // ── Common actions ───────────────────────────────────────────────────────
    save:              'Save',
    cancel:            'Cancel',
    delete:            'Delete',
    edit:              'Edit',
    add:               'Add',
    search:            'Search',
    loading:           'Loading...',
    saving:            'Saving...',
    deleting:          'Deleting...',
    actions:           'Actions',
    close:             'Close',
    confirm:           'Confirm',
    yes:               'Yes',
    no:                'No',
    saveChanges:       'Save Changes',
    createFirst:       'Create first booking',

    // ── Common fields ────────────────────────────────────────────────────────
    name:              'Name',
    phone:             'Phone',
    email:             'Email',
    address:           'Address',
    notes:             'Notes',
    date:              'Date',
    price:             'Price',
    discount:          'Discount',
    category:          'Category',
    type:              'Type',

    // ── Sidebar user menu ────────────────────────────────────────────────────
    myProfile:         'My Profile',
    configuration:     'Settings',
    logOut:            'Log out',

    // ── Contacts ─────────────────────────────────────────────────────────────
    clients:           'Clients',
    suppliers:         'Suppliers',
    addClient:         'Add Client',
    addSupplier:       'Add Supplier',
    addNewClient:      'Add New Client',
    addNewSupplier:    'Add New Supplier',
    editClient:        'Edit Client',
    editSupplier:      'Edit Supplier',
    deleteContact:     'Delete contact',
    deleteContactQ:    'Are you sure you want to delete this contact?',
    irreversible:      'This action cannot be undone.',
    clientAdded:       'Client added successfully',
    supplierAdded:     'Supplier added',
    changesSaved:      'Changes saved successfully',
    contactDeleted:    'Contact deleted',
    noClientsYet:      'No clients yet',
    noSuppliersYet:    'No suppliers yet',
    vehicleType:       'Vehicle Type',
    licensePlate:      'License Plate',
    supplierType:      'Supplier Type',
    totalSpent:        'Total Spent',
    mainVehicle:       'Main Vehicle',
    noVehiclesReg:     'No vehicles registered',
    lastBookings:      'Latest Bookings',
    noBookingsYet2:    'No bookings yet',
    searchPlaceholder: 'Search…',
    booking:           'booking',
    bookings2:         'bookings',

    // ── Bookings ──────────────────────────────────────────────────────────────
    bookingsCalendar:  'Bookings — Calendar',
    newBooking:        'New Booking',
    editBooking:       'Edit Booking',
    createBooking:     'Create Booking',
    updateBooking:     'Update Booking',
    bookingCreated:    'Booking created',
    bookingUpdated:    'Booking updated',
    bookingCompleted:  'Booking completed',
    bookingCancelled:  'Booking cancelled',
    markCompleted:     'Mark Completed',
    cancelBooking:     'Cancel Booking',
    selectClient:      'Select client…',
    selectVehicle:     'Select vehicle…',
    selectService:     'Select service…',
    startTime:         'Start Time',
    endTime:           'End Time',
    technicians:       'Technicians',
    clientAddress:     'Client Address',
    searchTechnician:  'Search technician…',
    noVehiclesReg2:    'No vehicles registered.',
    vehicleLabel:      'Vehicle',
    serviceLabel:      'Service',
    schedule:          'Schedule',
    priceAED:          'Price AED',
    discountAED:       'Discount AED',
    specialInstr:      'Special instructions…',

    // ── Vehicles ──────────────────────────────────────────────────────────────
    addVehicle:        'Add Vehicle',
    editVehicle:       'Edit Vehicle',
    vehicleAdded:      'Vehicle added',
    vehicleSaved:      'Vehicle saved',
    vehicleDeleted:    'Vehicle deleted',
    inRoute:           'In Route',
    available:         'Available',
    make:              'Make',
    model:             'Model',
    year:              'Year',
    color:             'Color',
    noVehiclesYet:     'No vehicles yet',

    // ── Services & Inventory ──────────────────────────────────────────────────
    servicesList:      'Services',
    inventoryList:     'Inventory',
    addService:        'Add Service',
    editService:       'Edit Service',
    addItem:           'Add Item',
    editItem:          'Edit Item',
    serviceAdded:      'Service added',
    serviceSaved:      'Service saved',
    serviceDeleted:    'Service deleted',
    itemAdded:         'Item added',
    itemSaved:         'Item saved',
    itemDeleted:       'Item deleted',
    description:       'Description',
    duration:          'Duration',
    stock:             'Stock',
    minStock:          'Min Stock',
    unit:              'Unit',
    noServicesYet:     'No services yet',
    noItemsYet:        'No items in inventory yet',
    lowStock:          'Low stock',

    // ── Finance ───────────────────────────────────────────────────────────────
    addExpense:        'Add Expense',
    revenue:           'Revenue',
    expenses:          'Expenses',
    netProfit:         'Net Profit',
    profitMargin:      'Profit Margin',
    fixedCosts:        'Fixed Costs',
    variableCosts:     'Variable Costs',
    operational:       'Operational',
    transactions:      'Transactions',
    noTransactions:    'No transactions yet',
    subCategory:       'Sub-Category',
    selectAccount:     'Select account…',
    expenseAdded:      'Expense added',
    expenseDeleted:    'Expense deleted',
    description2:      'Description',
    costsExpenses:     'Costs & Expenses',
    banks:             'Banks',
    chartOfAccounts:   'Chart of Accounts',
    taxes:             'Taxes',
    totalRevenueMTD:   'Total Revenue MTD',
    totalExpensesMTD:  'Total Expenses MTD',
    netProfitMTD:      'Net Profit MTD',
    expenseRegister:   'Expense Register',
    noExpenses:        'No expenses registered',
    noExpensesInCat:   'No expenses in this category',
    recurringMonthly:  'Recurring monthly',
    saveExpenseBtn:    'Save Expense',
    accounts:          'Accounts',
    bankSubtitle:      'Banks, credit cards & petty cash',
    addAccount:        'Add Account',
    noAccountsFound:   'No accounts found',
    reconcile:         'Reconcile',
    bankBalance:       'BANK BALANCE',
    cashOnHand:        'CASH ON HAND',
    creditCards:       'CREDIT CARDS',
    accountNumber:     'Account Number',
    reconciliation:    'Reconciliation',
    accountType:       'Account Type',
    balance:           'Balance',
    accountAdded:      'Account added',
    accountUpdated:    'Account updated',
    accountDeleted:    'Account deleted',

    // ── Reports ───────────────────────────────────────────────────────────────
    sales:             'Sales',
    administrative:    'Administrative',
    financialReports:  'Financial',
    clientReports:     'Clients',
    generateReport:    'Generate Report',
    downloadPDF:       'Download PDF',
    downloadExcel:     'Download Excel',
    sendEmail:         'Send by Email',
    sendWhatsApp:      'Send by WhatsApp',
    backToReports:     'Back to reports',
    tags:              'Tags',
    reportSent:        'Report sent',
    generate:          'Generate',
    export:            'Export',
    fiscal:            'Fiscal',
    workReports:       'Work Reports',
    exogenousInfo:     'Exogenous Info',
    favorites:         'Favorites',
    reportsSubtitle:   'Generate, download and share business reports',
    noFavoriteReports: 'No favorite reports',
    noFavoritesDesc:   'Mark reports as favorites to access them quickly from here',
    noSavedReports:    'No saved reports',
    reporte:           'report',
    reportes:          'reports',

    // ── Settings ──────────────────────────────────────────────────────────────
    teamRoles:         'Team & Roles',
    plans:             'Plans',
    billing:           'Billing',
    integrations:      'Integrations',
    inviteUser:        'Invite User',
    role:              'Role',
    permissions:       'Permissions',
    remove:            'Remove',
    readOnly:          'Read only — only administrators can modify permissions and team members.',
    adminOnly:         'Admin only',
    managerAdmin:      'Manager & Admin',
    companyName:       'Company Name',
    logoURL:           'Logo URL',
    savedChanges:      'Changes saved',
    teamMember:        'Team Member',
    inviteSent:        'Invite sent',
    memberRemoved:     'Member removed',
    confirmRemove:     'Are you sure you want to remove this member?',
    profile:           'Profile',
    businessProfile:   'Business Profile',
    generalSettings:   'General settings for your CRM',
    companyLogo:       'Company Logo',
    saveLogo:          'Save Logo',
    uploadLogo:        'Upload Logo',
    removeLogo:        'Remove Logo',
    businessName:      'Business Name',
    country:           'Country',
    currency:          'Currency',
    timezone:          'Timezone',
    interfaceLanguage: 'Language',
    members:           'members',
    inviteMember:      'Invite Member',
    connectApps:       'Connect third-party tools',
    choosePlan:        'Choose the plan that fits your business',
    manageSub:         'Manage your subscription and payment method',
    currentSubscription: 'Current Subscription',
    paymentMethod:     'Payment Method',
    invoiceHistory:    'Invoice History',
    download:          'Download',
  },

  es: {
    // ── Nav ──────────────────────────────────────────────────────────────────
    dashboard:         'Dashboard',
    contacts:          'Contactos',
    servicesInventory: 'Servicios e Inventario',
    vehicles:          'Vehículos',
    bookings:          'Reservas',
    finance:           'Finanzas',
    accounting:        'Contabilidad',
    reports:           'Reportes',
    settings:          'Configuración',

    // ── Dashboard KPIs ───────────────────────────────────────────────────────
    totalProfit:       'Ganancia Total',
    totalRevenue:      'Ingresos Totales',
    totalExpenses:     'Gastos Totales',
    lowStockAlerts:    'Stock Bajo',
    revenueMTD:        'Ingresos del Mes',
    activeBookings:    'Reservas Activas',
    avgOrderValue:     'Ticket Promedio',
    csatScore:         'Puntuación CSAT',
    recentBookings:    'Reservas Recientes',
    activityFeed:      'Actividad Reciente',
    currentMonth:      'Mes Actual',
    addChart:          'Agregar Gráfica',
    allInStock:        'todos en stock',
    noBookingsYet:     'Sin reservas aún',
    noActivityYet:     'Sin actividad aún',
    today:             'Hoy',
    thisWeek:          'Esta Semana',
    thisQuarter:       'Este Trimestre',
    thisYear:          'Este Año',
    comingSoon:        'Próximamente',
    last10:            'Últimas 10',
    client:            'Cliente',
    service:           'Servicio',
    vehicle:           'Vehículo',
    amount:            'Monto',
    status:            'Estado',

    // ── Common actions ───────────────────────────────────────────────────────
    save:              'Guardar',
    cancel:            'Cancelar',
    delete:            'Eliminar',
    edit:              'Editar',
    add:               'Agregar',
    search:            'Buscar',
    loading:           'Cargando...',
    saving:            'Guardando...',
    deleting:          'Eliminando...',
    actions:           'Acciones',
    close:             'Cerrar',
    confirm:           'Confirmar',
    yes:               'Sí',
    no:                'No',
    saveChanges:       'Guardar Cambios',
    createFirst:       'Crear primera reserva',

    // ── Common fields ────────────────────────────────────────────────────────
    name:              'Nombre',
    phone:             'Teléfono',
    email:             'Correo',
    address:           'Dirección',
    notes:             'Notas',
    date:              'Fecha',
    price:             'Precio',
    discount:          'Descuento',
    category:          'Categoría',
    type:              'Tipo',

    // ── Sidebar user menu ────────────────────────────────────────────────────
    myProfile:         'Mi perfil',
    configuration:     'Configuración',
    logOut:            'Cerrar sesión',

    // ── Contacts ─────────────────────────────────────────────────────────────
    clients:           'Clientes',
    suppliers:         'Proveedores',
    addClient:         'Agregar Cliente',
    addSupplier:       'Agregar Proveedor',
    addNewClient:      'Agregar Nuevo Cliente',
    addNewSupplier:    'Agregar Nuevo Proveedor',
    editClient:        'Editar Cliente',
    editSupplier:      'Editar Proveedor',
    deleteContact:     'Eliminar contacto',
    deleteContactQ:    '¿Seguro que deseas eliminar este contacto?',
    irreversible:      'Esta acción no se puede deshacer.',
    clientAdded:       'Cliente agregado correctamente',
    supplierAdded:     'Proveedor agregado',
    changesSaved:      'Cambios guardados correctamente',
    contactDeleted:    'Contacto eliminado',
    noClientsYet:      'No hay clientes aún',
    noSuppliersYet:    'No hay proveedores aún',
    vehicleType:       'Tipo de Vehículo',
    licensePlate:      'Matrícula',
    supplierType:      'Tipo de Proveedor',
    totalSpent:        'Gasto Total',
    mainVehicle:       'Vehículo Principal',
    noVehiclesReg:     'Sin vehículos registrados',
    lastBookings:      'Últimas Reservas',
    noBookingsYet2:    'Sin reservas aún',
    searchPlaceholder: 'Buscar…',
    booking:           'reserva',
    bookings2:         'reservas',

    // ── Bookings ──────────────────────────────────────────────────────────────
    bookingsCalendar:  'Reservas — Calendario',
    newBooking:        'Nueva Reserva',
    editBooking:       'Editar Reserva',
    createBooking:     'Crear Reserva',
    updateBooking:     'Actualizar Reserva',
    bookingCreated:    'Reserva creada',
    bookingUpdated:    'Reserva actualizada',
    bookingCompleted:  'Reserva completada',
    bookingCancelled:  'Reserva cancelada',
    markCompleted:     'Marcar Completada',
    cancelBooking:     'Cancelar Reserva',
    selectClient:      'Seleccionar cliente…',
    selectVehicle:     'Seleccionar vehículo…',
    selectService:     'Seleccionar servicio…',
    startTime:         'Hora Inicio',
    endTime:           'Hora Fin',
    technicians:       'Técnicos',
    clientAddress:     'Dirección del Cliente',
    searchTechnician:  'Buscar técnico…',
    noVehiclesReg2:    'Sin vehículos registrados.',
    vehicleLabel:      'Vehículo',
    serviceLabel:      'Servicio',
    schedule:          'Horario',
    priceAED:          'Precio AED',
    discountAED:       'Descuento AED',
    specialInstr:      'Instrucciones especiales…',

    // ── Vehicles ──────────────────────────────────────────────────────────────
    addVehicle:        'Agregar Vehículo',
    editVehicle:       'Editar Vehículo',
    vehicleAdded:      'Vehículo agregado',
    vehicleSaved:      'Vehículo guardado',
    vehicleDeleted:    'Vehículo eliminado',
    inRoute:           'En Ruta',
    available:         'Libre',
    make:              'Marca',
    model:             'Modelo',
    year:              'Año',
    color:             'Color',
    noVehiclesYet:     'Sin vehículos aún',

    // ── Services & Inventory ──────────────────────────────────────────────────
    servicesList:      'Servicios',
    inventoryList:     'Inventario',
    addService:        'Agregar Servicio',
    editService:       'Editar Servicio',
    addItem:           'Agregar Ítem',
    editItem:          'Editar Ítem',
    serviceAdded:      'Servicio agregado',
    serviceSaved:      'Servicio guardado',
    serviceDeleted:    'Servicio eliminado',
    itemAdded:         'Ítem agregado',
    itemSaved:         'Ítem guardado',
    itemDeleted:       'Ítem eliminado',
    description:       'Descripción',
    duration:          'Duración',
    stock:             'Stock',
    minStock:          'Stock Mínimo',
    unit:              'Unidad',
    noServicesYet:     'Sin servicios aún',
    noItemsYet:        'Sin ítems en inventario',
    lowStock:          'Stock bajo',

    // ── Finance ───────────────────────────────────────────────────────────────
    addExpense:        'Agregar Gasto',
    revenue:           'Ingresos',
    expenses:          'Gastos',
    netProfit:         'Ganancia Neta',
    profitMargin:      'Margen de Ganancia',
    fixedCosts:        'Costos Fijos',
    variableCosts:     'Costos Variables',
    operational:       'Operacional',
    transactions:      'Transacciones',
    noTransactions:    'Sin transacciones aún',
    subCategory:       'Sub-Categoría',
    selectAccount:     'Seleccionar cuenta…',
    expenseAdded:      'Gasto agregado',
    expenseDeleted:    'Gasto eliminado',
    description2:      'Descripción',
    costsExpenses:     'Costos y Gastos',
    banks:             'Bancos',
    chartOfAccounts:   'Plan de Cuentas',
    taxes:             'Impuestos',
    totalRevenueMTD:   'Ingresos Totales MTD',
    totalExpensesMTD:  'Gastos Totales MTD',
    netProfitMTD:      'Ganancia Neta MTD',
    expenseRegister:   'Registro de Gastos',
    noExpenses:        'No hay gastos registrados',
    noExpensesInCat:   'Sin gastos en esta categoría',
    recurringMonthly:  'Recurrente mensual',
    saveExpenseBtn:    'Guardar Gasto',
    accounts:          'Cuentas',
    bankSubtitle:      'Bancos, tarjetas y caja chica',
    addAccount:        'Agregar Cuenta',
    noAccountsFound:   'No se encontraron cuentas',
    reconcile:         'Conciliar',
    bankBalance:       'SALDO BANCARIO',
    cashOnHand:        'EFECTIVO DISPONIBLE',
    creditCards:       'TARJETAS DE CRÉDITO',
    accountNumber:     'Número de Cuenta',
    reconciliation:    'Conciliación',
    accountType:       'Tipo de Cuenta',
    balance:           'Saldo',
    accountAdded:      'Cuenta agregada',
    accountUpdated:    'Cuenta actualizada',
    accountDeleted:    'Cuenta eliminada',

    // ── Reports ───────────────────────────────────────────────────────────────
    sales:             'Ventas',
    administrative:    'Administrativos',
    financialReports:  'Financieros',
    clientReports:     'Clientes',
    generateReport:    'Generar Reporte',
    downloadPDF:       'Descargar PDF',
    downloadExcel:     'Descargar Excel',
    sendEmail:         'Enviar por Email',
    sendWhatsApp:      'Enviar por WhatsApp',
    backToReports:     'Volver a reportes',
    tags:              'Etiquetas',
    reportSent:        'Reporte enviado',
    generate:          'Generar',
    export:            'Exportar',
    fiscal:            'Fiscales',
    workReports:       'Para trabajar',
    exogenousInfo:     'Información exógena',
    favorites:         'Favoritos',
    reportsSubtitle:   'Genera, descarga y comparte reportes del negocio',
    noFavoriteReports: 'Sin reportes favoritos',
    noFavoritesDesc:   'Marca reportes como favoritos para acceder rápido desde aquí',
    noSavedReports:    'Sin reportes guardados',
    reporte:           'reporte',
    reportes:          'reportes',

    // ── Settings ──────────────────────────────────────────────────────────────
    teamRoles:         'Equipo y Roles',
    plans:             'Planes',
    billing:           'Facturación',
    integrations:      'Integraciones',
    inviteUser:        'Invitar Usuario',
    role:              'Rol',
    permissions:       'Permisos',
    remove:            'Eliminar',
    readOnly:          'Solo lectura — solo los administradores pueden modificar permisos y miembros del equipo.',
    adminOnly:         'Solo admin',
    managerAdmin:      'Manager y Admin',
    companyName:       'Nombre de Empresa',
    logoURL:           'URL del Logo',
    savedChanges:      'Cambios guardados',
    teamMember:        'Miembro del Equipo',
    inviteSent:        'Invitación enviada',
    memberRemoved:     'Miembro eliminado',
    confirmRemove:     '¿Seguro que deseas eliminar a este miembro?',
    profile:           'Perfil',
    businessProfile:   'Perfil Empresarial',
    generalSettings:   'Configuración general del CRM',
    companyLogo:       'Logo de la empresa',
    saveLogo:          'Guardar logo',
    uploadLogo:        'Subir logo',
    removeLogo:        'Eliminar logo',
    businessName:      'Nombre Empresarial',
    country:           'País',
    currency:          'Moneda',
    timezone:          'Zona Horaria',
    interfaceLanguage: 'Idioma',
    members:           'miembros',
    inviteMember:      'Invitar Miembro',
    connectApps:       'Conectar apps de terceros',
    choosePlan:        'Elige el plan que se adapta a tu negocio',
    manageSub:         'Administra tu suscripción y método de pago',
    currentSubscription: 'Suscripción Actual',
    paymentMethod:     'Método de Pago',
    invoiceHistory:    'Historial de Facturas',
    download:          'Descargar',
  },
}

type Lang = 'en' | 'es'
export type TranslationKey = keyof typeof translations.en

interface LangCtx {
  lang: Lang
  setLang: (l: Lang) => void
  t: (k: TranslationKey) => string
}

const LanguageContext = createContext<LangCtx>({
  lang: 'en',
  setLang: () => {},
  t: (k) => k,
})

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>('en')

  useEffect(() => {
    const stored = localStorage.getItem('noirem-lang') as Lang | null
    if (stored === 'en' || stored === 'es') setLangState(stored)
  }, [])

  function setLang(l: Lang) {
    setLangState(l)
    localStorage.setItem('noirem-lang', l)
  }

  const t = (key: TranslationKey): string => translations[lang][key] ?? key

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
